### PR TITLE
fix: select connected DRM card for KMSCube  

### LINKED ISSUE #420: Graphics test failure on lemans Ridesx devices
We are seeing graphics test failure even though display test case is passing and display connected

kmscube is unable to successfully initialize legacy DRM modesetting on the MSM driver after Weston had previously acquired DRM master. Although the logs clearly show a connected and enabled display on card1 (DP 3 @ 1920×1080), atomic modesetting is not supported, forcing kmscube to rely on legacy KMS, which is sensitive to both DRM master ownership and correct DRM card selection. After stopping Weston, DRM master is not cleanly or reliably handed over, and kmscube likely opens the wrong DRM device leading it to report “no connected connector” despite the display being present and valid

Lava job: [LAVA | Scheduler | Jobs | 185555](https://lava.infra.foundries.io/scheduler/job/185555)

[WARN] 2026-03-13 15:35:33 - display_is_cpu_renderer gbm not supported, falling back to auto (may touch Wayland/Weston).[INFO] 2026-03-13 15:35:33 - ---------------- EGLINFO pipeline detection (select one) ----------------[INFO] 2026-03-13 15:35:33 - EGLINFO: Pipeline type: GPU (hardware)[INFO] 2026-03-13 15:35:33 - EGLINFO: Pipeline=WAYLAND platform:[INFO] 2026-03-13 15:35:33 - EGLINFO: EGL driver name: msm[INFO] 2026-03-13 15:35:33 - EGLINFO: GL_VENDOR: freedreno[INFO] 2026-03-13 15:35:33 - EGLINFO: GL_RENDERER: FD663[INFO] 2026-03-13 15:35:33 - ---------------- End EGLINFO pipeline detection --------------------------[INFO] 2026-03-13 15:35:33 - Weston is running, stopping it so kmscube can modeset (DRM master)[INFO] 2026-03-13 15:35:33 - Running kmscube with --count=999 ...[FAIL] 2026-03-13 15:35:33 - KMSCube : Execution failed (rc=255) — see ./KMSCube_run.logno connected connector!failed to initialize legacy DRM[INFO] 2026-03-13 15:35:33 - Restoring Weston after failure+ true+ /home/lava-185555/0/tests/1_KMSCube/Runner/utils/send-to-lava.sh KMSCube.res<<<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=KMSCube RESULT=FAIL>>>+ set +xReceived signal: <TESTCASE> TEST_CASE_ID=KMSCube RESULT=FAIL

Thanks,
Bhargav

### PR DESCRIPTION
**Pull request by smuppand**
Fixes #420
 
This PR fixes KMSCube failures on multi-DRM-card platforms where a valid display is connected but kmscube still fails with:
 
  no connected connector!
  failed to initialize legacy DRM
 
Why this PR is needed:
- On affected platforms such as Lemans RideSX, sysfs reports a connected and   enabled display on a specific DRM card, for example card1-DP-3.
- The existing KMSCube test only checked that some display was connected, but   then ran kmscube without specifying the DRM device.
- On systems with multiple DRM cards, kmscube may auto-open a different card   that has no connected connector, causing a false test failure even though a   monitor is attached and valid.
- This is especially visible when kmscube falls back to legacy DRM modesetting,   where correct DRM card selection is required.

### CODE REVIEW

**Comment by smuppand** [comment]
Refer the job with these changes: https://lava.infra.foundries.io/scheduler/job/189609

File: Runner/utils/lib_display.sh [hunk 1]
```diff
@@ -381,6 +381,29 @@ display_select_primary_connector() {
...
+    card_idx="$(display__drm_idx_from_sysfs_connector "$connector" 2>/dev/null || true)"
+    case "$card_idx" in
+        ""|*[!0-9]*)
+            return 1
+            ;;
+    esac
+
+    card_dev="/dev/dri/card$card_idx"
+    [ -e "$card_dev" ] || return 1
+
```
Comment (abbajaj806) [inline Runner/utils/lib_display.sh:420]: Same. Silent failures are hard to debug.

File: Runner/utils/lib_display.sh [hunk 2]
```diff
@@ -381,6 +381,29 @@ display_select_primary_connector() {
...
+# Select the DRM card device that owns the preferred connected display.
+# Prints /dev/dri/cardN when a real connected connector is available.
+display_select_primary_drm_device() {
+    connector=""
+    card_idx=""
+    card_dev=""
+
+    connector="$(display_select_primary_connector 2>/dev/null || true)"
+    [ -n "$connector" ] || return 1
+
```
Comment (abbajaj806) [inline Runner/utils/lib_display.sh:407]: Silent failures are hard to debug
Consider wrapping suppressed calls with a debug flag:
Ex:
connector="$(display_select_primary_connector 2>&1)" || {
    _dbg "display_select_primary_connector failed: $connector"
    return 1
}

File: Runner/suites/Multimedia/Graphics/KMSCube/run.sh [hunk 3]
```diff
@@ -81,13 +83,31 @@ if [ "$have_connector" -eq 0 ]; then
     exit 0
 fi
 
+# Select the DRM card that owns the connected display.
+# This avoids kmscube auto-selecting the wrong card on multi-DRM-card systems.
```
Comment (abbajaj806) [inline Runner/suites/Multimedia/Graphics/KMSCube/run.sh:87]: Suggested: initialize at the top to avoid stale values from outer scope

KMSCUBE_DRM_CONNECTOR=""
KMSCUBE_DRM_DEV=""

**Review by abbajaj806 — CHANGES_REQUESTED** [review]

File: Runner/suites/Multimedia/Graphics/KMSCube/run.sh (hunk 3 above)
Comment (smuppand) [reply Runner/suites/Multimedia/Graphics/KMSCube/run.sh:87]: These are only initialized at the top.

File: Runner/utils/lib_display.sh (hunk 1 above)
Comment (smuppand) [reply Runner/utils/lib_display.sh:420]: > Same. Silent failures are hard to debug.

ACK.. made changes which will help for debugging

File: Runner/utils/lib_display.sh (hunk 2 above)
Comment (smuppand) [reply Runner/utils/lib_display.sh:407]: > Silent failures are hard to debug Consider wrapping suppressed calls with a debug flag: Ex: connector="$(display_select_primary_connector 2>&1)" || { _dbg "display_select_primary_connector failed: $connector" return 1 }

ACK, made changes to help for debugging

**Review by abbajaj806 — APPROVED** [review]
LGTM
